name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v1

    - name: Cache Lean dependencies
      uses: actions/cache@v1
      with:
        path: _target
        key: ${{ runner.OS }}-build-${{ hashFiles('leanpkg.toml') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install elan
      run: curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y

    - name: Install Lean
      run: |
        source ~/.elan/env
        leanpkg configure

    - name: "Check Lean code"
      run: |
        source ~/.elan/env
        leanpkg build
