name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install elan
      run: curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    - name: Install Lean
      run: |
        source ~/.elan/env
        leanpkg configure
    - name: "Check Lean code"
      run: |
        source ~/.elan/env
        leanpkg build -- -t0
